### ISSUE TITLE
[BUG]: Conda dependencies for examples installs CPU build of PyTorch

### ISSUE THREAD

**Issue by efajardo-nv** [nv-morpheus/Morpheus#1366]
### Version

fea-sherlock

### Which installation method(s) does this occur on?

Conda

### Describe the bug.

I have a Morpheus conda environment created using https://github.com/nv-morpheus/Morpheus/blob/fea-sherlock/docker/conda/environments/cuda11.8_dev.yml. When I try to run LLM RAG pipeline, it fails with error:

```
AssertionError: Torch not compiled with CUDA enabled
```

This is because the following step to add the examples dependencies replaces CUDA build of PyTorch with the CPU build:
```
mamba env update -n morpheus --file ${MORPHEUS_ROOT}/docker/conda/environments/cuda11.8_examples.yml
```

### Minimum reproducible example

Example LLM RAG pipeline in Morpheus dev conda environment:
https://github.com/nv-morpheus/Morpheus/blob/fea-sherlock/examples/llm/rag/README.md

### Relevant log output

```
Exception occurred in pipeline. Rethrowing
Traceback (most recent call last):
  File "/opt2/gitrepos/efajardo-nv/Morpheus/morpheus/pipeline/pipeline.py", line 385, in join
    await self._mrc_executor.join_async()
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
  File "/opt2/gitrepos/efajardo-nv/Morpheus/morpheus/llm/nodes/retriever_node.py", line 86, in execute
    embeddings = await self._embedding(input_strings)
  File "/opt2/gitrepos/efajardo-nv/Morpheus/examples/llm/rag/standalone_pipeline.py", line 67, in calc_embeddings
    return embeddings.embed_documents(texts)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/langchain/embeddings/huggingface.py", line 78, in embed_documents
    embeddings = self.client.encode(texts, **self.encode_kwargs)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/sentence_transformers/SentenceTransformer.py", line 153, in encode
    self.to(device)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/efajardo/miniconda3/envs/morpheus/lib/python3.10/site-packages/torch/cuda/__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

### Code of Conduct

- [X] I agree to follow Morpheus' Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/Morpheus/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by efajardo-nv** [comment]
I'm able to successfully install packages in `cuda11.8_examples.yml` individually. When I update with the yaml, something is replacing the `mkl` implementation of `blas` with the `openblas` implementation. This forces PyTorch to be replaced with the CPU version that's compatible with `openblas`. I was able to fix this by adding the following to the yaml which prevents `openblas` from being installed.

```
"libblas=*=*mkl"
```

However, the yaml still doesn't work when used in DEV container (issue #1369).

**Comment by efajardo-nv** [comment]
Appears to be issue with mamba solver when using `mamba env update` to add the dependencies to an existing `morpheus` conda environment. If I create a combined yaml that includes both the dev and examples dependencies, I'm able to use it to build a new environment that has all the correct dependencies (dev + examples).

**Comment by efajardo-nv** [comment]
Fixed by #1387
